package com.kaikeventura.simplestatemachine.model;

public enum PaymentEvent {
    CHECK_APPROVE_PAYMENT,
    APPROVE_PAYMENT,
    NO_APPROVE_PAYMENT,
    CHECK_COMPLETE_PAYMENT,
    COMPLETE_PAYMENT,

    CANCEL_PAYMENT,
    APPROVE_CANCELLATION_PAYMENT,
    COMPLETE_CANCELLATION_PAYMENT,
    NO_APPROVE_CANCELLATION_PAYMENT
}
